FROM python:3.8
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY actions ./
# expose the port at which we'll run our app
EXPOSE 5055

# sleep to wait for sql server to boot then run our app
CMD sleep 5; rasa run actions;